name: Dev Card

on:
  workflow_dispatch:

  push:
    branches:
      - main

  schedule:
    - cron: "0 18 * * *"

jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@3.2.1
        with:
          user_id: ${{ secrets.USER_ID }}
          commit_message: "update ${filename}"
